version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "585768158376"
    AWS_REGION: "us-east-1"
    ECR_REPOSITORY_CLIENTE: "cliente"
    ECR_REPOSITORY_SERVIDOR: "servidor"
    IMAGE_TAG: "latest"
    TF_VAR_cliente_image: "public.ecr.aws/y5w8k0j6/cliente:latest"
    TF_VAR_servidor_image: "public.ecr.aws/y5w8k0j6/servidor:latest"
    WORKSPACE: "prod"
   
phases:
  install:
    commands:
      - echo "Instalando Docker..."
      - yum update -y
      - yum install -y docker
      - echo "Iniciando Docker en segundo plano..."
      - nohup dockerd &>/var/log/dockerd.log &
      - timeout 15 sh -c "until docker info; do echo 'Esperando a Docker...' && sleep 1; done"
      - echo "Docker iniciado exitosamente."
      - curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - echo "Instalando Terraform v1.0.3..."
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/bin/
      - terraform version
      
  pre_build:
    commands:
      - echo "Iniciando sesi칩n en Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Construyendo las im치genes Docker..."
      - docker-compose build
      - echo "Etiquetando im치genes para Amazon ECR..."
      - docker tag cliente:latest public.ecr.aws/y5w8k0j6/cliente:latest
      - docker tag servidor:latest public.ecr.aws/y5w8k0j6/servidor:latest
      - echo "Subiendo im치genes a Amazon ECR..."
      - docker push public.ecr.aws/y5w8k0j6/cliente:latest
      - docker push servidor:latest public.ecr.aws/y5w8k0j6/servidor:latest

  post_build:
    commands:
      - echo "Listando archivos del proyecto..."
      - ls -al
      - echo "Cambiando al directorio de Terraform (app)..."
      - cd app
      - echo "Inicializando Terraform en el directorio 'app'..."
      - terraform init      
      - terraform workspace select $WORKSPACE
      - echo "Workspace donde se va a desplegar..."
      - terraform workspace show
      - echo "Planeando la infraestructura con Terraform..."
      - terraform plan -out=tfplan
      - echo "Aplicando cambios con Terraform..."
      - terraform apply -auto-approve tfplan


artifacts:
  files:
    - "**/*"
